services:
  bigquery:
    image: ghcr.io/goccy/bigquery-emulator:latest
    ports:
      - "${BIGQUERY_PORT:-9050}:9050"
      - "${BIGQUERY_GRPC_PORT:-9060}:9060"
    command: --project=$${GOOGLE_CLOUD_PROJECT:-emulator-test-project} --dataset=$${BIGQUERY_DATASET:-test-dataset}
networks:
  default:
    driver: bridge
